import MainProvider from "@/components/providers/main-provider/MainProvider";
import type { Metadata } from "next";
import localFont from "next/font/local";

const myFont = localFont({
  src: [
    {
      path: "../assets/fonts/static/StyreneAWeb-Light.ttf",
      weight: "300",
      style: "light",
    },
    {
      path: "../assets/fonts/static/StyreneAWeb-Regular.ttf",
      weight: "400",
      style: "normal",
    },
    {
      path: "../assets/fonts/static/StyreneAWeb-Medium.ttf",
      weight: "500",
      style: "medium",
    },
    {
      path: "../assets/fonts/static/StyreneAWeb-Bold.ttf",
      weight: "700",
      style: "bold",
    },
  ],
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={myFont.className}>
        <MainProvider>{children}</MainProvider>
      </body>
    </html>
  );
}
